---
title: "Analysis"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: hide
    number_sections: yes
editor_options:
  chunk_output_type: console
---
# Setup

```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	results = "asis",
	message = FALSE,
	warning = FALSE, 
	fig.height = 18, 
	fig.width = 11, 
	cache = TRUE
)
options(scipen=9999) # desactivar notacion cientifica
remove(list = ls()) #limpieza del entorno de trabajo
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

# A. Frecuencia: asiste a marchar

## Descriptivos

```{r tab-desc, results="asis", warning=FALSE}
if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               ggplot2,
               sjPlot,
               tidyverse,
               ggalluvial,
               survey,
               shadowtext,
               srvyr
               )
load(file = here::here("input/data-proc/df_study1_long_t6.RData"))

# Css
st_css()
st_options(lang = "en",
           footnote = NA,
           bootstrap.css = F,
           custom.css = here::here("input/css/dfsummary.css"),
           dfSummary.custom.1 = NA
           )  

# Df variables nivel 1
# df<- dfSummary(df_study1_long %>% select(in_simpat:edad),
#                plain.ascii = FALSE,
#                style = "grid",
#                tmp.img.dir = "/tmp",
#                graph.magnif = TRUE,
#                headings = F,  # encabezado
#                varnumbers = F, # num variable
#                labels.col = T, # etiquetas
#                na.col = F,    # missing
#                graph.col = T, # plot
#                valid.col = T, # n valido
#                col.widths = c(700,10,10,10,10)
#                )
# df$Variable <- NULL # delete variable column
# view(df,
#      file = here::here("output/tables/desc01.html")
#      ) # Ver tabla en un archivo HTML
# webshot::webshot(url =here::here("output/tables/desc01.html"),
#         file =here::here("output/tables/desc01.png")) # Remover archivo HTML
# # print(df, method = "render")

# Df variables nivel 1 _________________________________________________________
df_study1 <- df_study1_long_t6 %>% dplyr::select(idencuesta,ola,region_cod,comuna,
         sexo,
         pos_id,
         edad,
         educ,
         quintil1,
         ess,
         starts_with("barrio_"),
         starts_with("satisfaccion_"),
         marchar
         )

df_study1$ola <- factor(df_study1$ola,
         labels = c("2016","2017","2018","2019", "2021", "2022"))
df_study1$ola <- 
sjlabelled::set_label(x = df_study1$ola,
                      label = "Ola")

df_study1$sexo <- factor(df_study1$sexo,
         labels = c("Hombre", "Mujer"))
df_study1$sexo <- 
sjlabelled::set_label(x = df_study1$sexo,
                      label = "Sexo")

# for (i in c("just_educ", "des_perc",
#             "merit_effort","merit_talent")) {
#   df_study1[[i]] <- factor(df_study1[[i]],
#                             levels = 1:5,
#                             labels = c("Strongly disagree","Disagree",
#                                        "Neither disagree nor agree",
#                                        "Agree", "Strongly agree"))
# }



df_study1$marchar <- 
sjlabelled::set_label(x = df_study1$marchar, 
                      label = "Frecuencia: asiste a marchar")

df_study1$part_com <- 
sjlabelled::set_label(x = df_study1$part_com, 
                      label = "Frecuencia: reuniones publicas/comunitarias")
# #
# df_study1$des_perc <- 
# sjlabelled::set_label(x = df_study1$des_perc, 
#                       label = "Income differences are too large") 
# 
# #
# df_study1$merit_effort <- 
# sjlabelled::set_label(x = df_study1$merit_effort, 
#                       label = "People are rewarded for their efforts")
# 
# #
# df_study1$merit_talent <- 
# sjlabelled::set_label(x = df_study1$merit_talent, 
#                       label = "People are rewarded for their intelligence and skills")


lab_study1 <- sjlabelled::get_label(df_study1) 
df_study1 <- df_study1 %>% na.omit() %>% sjlabelled::set_label(lab_study1)

df<- dfSummary(x = dplyr::select(df_study1, marchar, starts_with("barrio_"), starts_with("satisfaccion_"), educ, quintil1, ess, edad, sexo, pos_id),
               plain.ascii = FALSE,
               style = "grid",
               tmp.img.dir = "/tmp",
               graph.magnif = TRUE,
               headings = F,  # encabezado
               varnumbers = F, # num variable
               labels.col = T, # etiquetas
               na.col = F,    # missing
               graph.col = T, # plot
               valid.col = F, # n valido
               col.widths = c(700,10,10,10)
               )
df$Variable <- NULL # delete variable column
summarytools::view(df,
     file = here::here("output/tables/desc02.html")
     ) # Ver tabla en un archivo HTML
webshot::webshot(url =here::here("output/tables/desc02.html"),
        file =here::here("output/tables/desc02.png")) # Remover archivo HTML
# print(df, method = "render")
```

```{r}
load(file = here::here("input/data-proc/df_study1_long_t6.RData"))
df_study1 <- df_study1_long_t6 %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                                marchar, starts_with("barrio_"), starts_with("satisfaccion_"),
                                                educ, quintil1, ess, edad, sexo, pos_id) %>% na.omit()
df_study1 <- df_study1[complete.cases(df_study1$segmento), ]

df_study1$marchar <- factor(df_study1$marchar,
         labels = c("Nunca", "Casi nunca", "A veces", "Frecuentemente", "Muy 
frecuentemente"))

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador_long_total, #ponderador longitudinal
                          nest = TRUE,
                          data = df_study1)


#Paso 1
datos.marchar <- data.frame((svytable(~marchar + ola + idencuesta, elsoc_diseno, round = F))) %>% dplyr::filter(Freq>0)  %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#Paso 2
etiquetas.marchar <- data.frame((svytable(~marchar + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit() %>% 
  mutate(idencuesta = 1)
datos.marchar$marchar <- factor(datos.marchar$marchar, levels = rev(levels(datos.marchar$marchar)))
etiquetas.marchar$marchar <- factor(etiquetas.marchar$marchar, levels = rev(levels(etiquetas.marchar$marchar)))
```

```{r alluvial}
colors<- c("#f1eef6ff","#bdc9e1ff","#b3b3b3ff","#74a9cfff","#0570b0ff")
alluvial_marchar <- ggplot(datos.marchar, aes(x = ola, fill = marchar, stratum = marchar,
                             alluvium = idencuesta, y = porcentaje))+
    ggalluvial::geom_flow(alpha = .66) + 
    ggalluvial::geom_stratum(linetype = 0) +
    scale_y_continuous(labels = scales::percent) + 
    ylab(label = NULL) +
    xlab(label = NULL) + 
    theme(#legend.position = 'top',
          legend.title = element_blank(),
          plot.caption = element_text(hjust = 1)) +
    scale_fill_manual(values = colors) +
    geom_shadowtext(data = etiquetas.marchar, 
              aes(label = ifelse(porcentaje > 0 , scales::percent(porcentaje, accuracy = .1),"")),
              position = position_stack(vjust = .5),
              show.legend = FALSE,
              size = 4,
              color = rep('white'),
              bg.colour='grey30')+
  scale_x_discrete(labels = c(2016, 2017, 2018, 2019, 2022))

alluvial_marchar

ggsave(alluvial_marchar, file="output/graphs/alluvial_dep.png", height = 8, width = 7)
```

```{r bivariate-plots}
df_study1 <- df_study1_long_t6 %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                               marchar, starts_with("barrio_"),
                                                educ, quintil1, ess, edad, sexo, pos_id) %>% na.omit()
cohesion_plot <- df_study1 %>% 
  select(starts_with("barrio_"), starts_with("satisfaccion_")) %>% 
  sjPlot::plot_stackfrq(weight.by = df_study1$ponderador_long_total,
                        expand.grid =TRUE,
                      geom.colors = "PuBu",
                      show.total = FALSE, 
         #             vjust=rep(c("bottom", "top", "bottom", "top", "bottom"),4),
                      legend.labels = c("Muy en desacuerdo", "Desacuerdo", "Ni de acuerdo
Ni desacuerdo", "De acuerdo", "Muy de acuerdo"),
#                       axis.labels = c("Merit effort", "Merit talent", "Inequality 
# perception", "Justification 
# of 
# educational inequality")
                      ) +
  theme_light(base_size = 16) +
  theme(legend.position="bottom", text = element_text(size = 14),
        plot.caption = element_text(hjust = 1))
cohesion_plot

ggsave(cohesion_plot, file="output/graphs/cohesion_plot.png", height = 6, width = 10)
```

```{r bivariate-plots2}
df_study1 <- df_study1_long_t6 %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                               marchar, starts_with("satisfaccion_"),
                                                educ, quintil1, ess, edad, sexo, pos_id) %>% na.omit()
satisfaccion_plot <- df_study1 %>% 
  select(starts_with("barrio_"), starts_with("satisfaccion_")) %>% 
  sjPlot::plot_stackfrq(weight.by = df_study1$ponderador_long_total,
                        expand.grid =TRUE,
                      geom.colors = "PuBu",
                      show.total = FALSE, 
         #             vjust=rep(c("bottom", "top", "bottom", "top", "bottom"),4),
                      legend.labels = c("Muy en desacuerdo", "Desacuerdo", "Ni de acuerdo
Ni desacuerdo", "De acuerdo", "Muy de acuerdp"),
#                       axis.labels = c("Merit effort", "Merit talent", "Inequality 
# perception", "Justification 
# of 
# educational inequality")
                      ) +
  theme_light(base_size = 16) +
  theme(legend.position="bottom", text = element_text(size = 14),
        plot.caption = element_text(hjust = 1))
satisfaccion_plot

ggsave(satisfaccion_plot, file="output/graphs/satisfaccion_plot.png", height = 6, width = 10)
```


## Regresión


```{r marchar}
rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study1_long_t6.RData"))

# generate analytical sample
df_study1 <- 
  df_study1_long_t6 %>%
  select(idencuesta,ola,comuna, region_cod, ponderador_long_total, marchar, starts_with("barrio_"), starts_with("satisfaccion_"), educ, quintil1, ess, edad, sexo, pos_id) %>% 
  na.omit() %>% 
  mutate(ola_num=as.numeric(ola),
         ola_2 = ola_num^2,
         ola=as.factor(ola),
         sexo=as.factor(sexo)
         )
# Hipotesis
h1 <- "ola"
h2 <- "ola_num"
h3 <- "ola_2"
h4 <- "ola_num+ola_2"

marchar.null <- lmer(formula(paste0("marchar~","1 + (1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar1 <- lmer(formula(paste0("marchar~",h1,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar2 <- lmer(formula(paste0("marchar~",h2,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar3 <- lmer(formula(paste0("marchar~",h3,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar4 <- lmer(formula(paste0("marchar~",h4,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)

performance::icc(marchar.null)
```


```{r marchar-reg, results='asis'}
texreg::htmlreg(list(marchar.null, marchar1, marchar2, marchar3, marchar4),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05")
```


```{r marchar2}
sjmisc::frq(df_study1$region_cod)
df_study1 <- df_study1 %>% mutate(rm= case_when(region_cod==13~"RM",
                                                TRUE~"Otra región"))
sjmisc::frq(df_study1$rm)

df_study1 <- df_study1 %>% 
  rowwise() %>%
  mutate(cohesion_barrial = mean(c(barrio_ideal, barrio_integrado, barrio_identifico, barrio_partedemi)),
         sociabilidad_barrial = mean(c(barrio_amigos, barrio_sociable, barrio_cordial, barrio_colaboradora)),
         satisfaccion_residencial= mean(c(satisfaccion_seguridad, satisfaccion_conectivdad, satisfaccion_areasverdes, satisfaccion_limpieza, satisfaccion_proximidadtrabajo, satisfaccion_proximidadcolegios, satisfaccion_proximidadcomercio, satisfaccion_proximidadfamilia))) %>% 
  ungroup()


h5 <- "ola+edad"
h6 <- "ola+edad+rm"
h7 <- "ola+edad+rm+cohesion_barrial"
h8 <- "ola+edad+rm+sociabilidad_barrial"
h9 <- "ola+edad+rm+satisfaccion_residencial"
h10 <- "ola+edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial"
h11 <- "ola+edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"
h12 <- "ola*edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"
h13 <- "ola*educ+edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"
h14 <- "edad*educ*ola+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"

# A. Education distributive justice

marchar5 <- lmer(formula(paste0("marchar~",h5,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar6 <- lmer(formula(paste0("marchar~",h6,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar7 <- lmer(formula(paste0("marchar~",h7,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar8 <- lmer(formula(paste0("marchar~",h8,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar9 <- lmer(formula(paste0("marchar~",h9,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar10 <- lmer(formula(paste0("marchar~",h10,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar11 <- lmer(formula(paste0("marchar~",h11,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar12 <- lmer(formula(paste0("marchar~",h12,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar13 <- lmer(formula(paste0("marchar~",h13,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar14 <- lmer(formula(paste0("marchar~",h14,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
```

### Modelos de regresión

```{r marchar2-reg, results='asis'}
#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(marchar1, marchar5, marchar6, marchar7, marchar8, marchar9, marchar10, marchar11),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
#                custom.coef.names = c("Intercepto",
#                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
#                                      "ola 2018",
#                                      "ola 2019",
##                                      "ola 2022",
#                                      "Merito: esfuerzo",
#                                      "Merito: Inteligencia",
##                                      "Goahead: Familia",
#                                      "Goahead: educacion",
#                                      "Goahead: ambicion",
#                                      "Goahead: trabajo duro",
#                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
#                                      "Ed. técnica",
#                                      "Ed. universitaria",
#                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
#                                      "Quintil 3",
#                                      "Quintil 4",
#                                      "Quintil 5",
#                                      "Quintil NA",
#                                      "Estatus social subjetivo",
#                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
#                                      "Pos. política: Derecha",
#                                      "Pos. política: No se identifica",
#                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
#                                      "Edad 50-64",
#                                      "Edad 65 o más",
#                                      "Mujer <br> <i>(Ref. Hombre)</i>",
#                                      "Gini comunal",
#                                      "Cambio gini 2022-2017",
#                                      "Proporción educ universitaria",
#                                      "Proporción matrícula privada",
#                                      "Total matrícula privada",
#                                      "Varianza Simce comuna",
#                                      "Promedio Simce comuna"
                                    
                              )
          #omit.coef = omit

```

### interacciones

```{r marchar-interac, results='asis'}
#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(marchar12, marchar13, marchar14),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
#                custom.coef.names = c("Intercepto",
#                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
#                                      "ola 2018",
#                                      "ola 2019",
##                                      "ola 2022",
#                                      "Merito: esfuerzo",
#                                      "Merito: Inteligencia",
##                                      "Goahead: Familia",
#                                      "Goahead: educacion",
#                                      "Goahead: ambicion",
#                                      "Goahead: trabajo duro",
#                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
#                                      "Ed. técnica",
#                                      "Ed. universitaria",
#                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
#                                      "Quintil 3",
#                                      "Quintil 4",
#                                      "Quintil 5",
#                                      "Quintil NA",
#                                      "Estatus social subjetivo",
#                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
#                                      "Pos. política: Derecha",
#                                      "Pos. política: No se identifica",
#                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
#                                      "Edad 50-64",
#                                      "Edad 65 o más",
#                                      "Mujer <br> <i>(Ref. Hombre)</i>",
#                                      "Gini comunal",
#                                      "Cambio gini 2022-2017",
#                                      "Proporción educ universitaria",
#                                      "Proporción matrícula privada",
#                                      "Total matrícula privada",
#                                      "Varianza Simce comuna",
#                                      "Promedio Simce comuna"
                                    
                              )
          #omit.coef = omit

```

```{r}
sjPlot::plot_model(marchar12, type = "int")
```


```{r}
sjPlot::plot_model(marchar13, type = "int")
```

```{r}
sjPlot::plot_model(marchar14, type = "int")
```


# B. Frecuencia: asiste a reuniones de interés publico/comunitario

## Descriptivos

```{r}
load(file = here::here("input/data-proc/df_study1_long_t6.RData"))
df_study1 <- df_study1_long_t6 %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                                part_com, starts_with("barrio_"), starts_with("satisfaccion_"),
                                                educ, quintil1, ess, edad, sexo, pos_id) %>% na.omit()
df_study1 <- df_study1[complete.cases(df_study1$segmento), ]

df_study1$part_com <- factor(df_study1$part_com,
         labels = c("Nunca", "Una o dos veces", "Más de dos veces"))

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador_long_total, #ponderador longitudinal
                          nest = TRUE,
                          data = df_study1)


#Paso 1
datos.part_com <- data.frame((svytable(~part_com + ola + idencuesta, elsoc_diseno, round = F))) %>% dplyr::filter(Freq>0)  %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#Paso 2
etiquetas.part_com <- data.frame((svytable(~part_com + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit() %>% 
  mutate(idencuesta = 1)
datos.part_com$part_com <- factor(datos.part_com$part_com, levels = rev(levels(datos.part_com$part_com)))
etiquetas.part_com$part_com <- factor(etiquetas.part_com$part_com, levels = rev(levels(etiquetas.part_com$part_com)))
```

```{r alluvial-part-com}
colors<- c("#b3b3b3ff","#74a9cfff","#0570b0ff")
alluvial_part_com <- ggplot(datos.part_com, aes(x = ola, fill = part_com, stratum = part_com,
                             alluvium = idencuesta, y = porcentaje))+
    ggalluvial::geom_flow(alpha = .66) + 
    ggalluvial::geom_stratum(linetype = 0) +
    scale_y_continuous(labels = scales::percent) + 
    ylab(label = NULL) +
    xlab(label = NULL) + 
    theme(#legend.position = 'top',
          legend.title = element_blank(),
          plot.caption = element_text(hjust = 1)) +
    scale_fill_manual(values = colors) +
    geom_shadowtext(data = etiquetas.part_com, 
              aes(label = ifelse(porcentaje > 0 , scales::percent(porcentaje, accuracy = .1),"")),
              position = position_stack(vjust = .5),
              show.legend = FALSE,
              size = 4,
              color = rep('white'),
              bg.colour='grey30')+
  scale_x_discrete(labels = c(2016, 2017, 2018, 2019, 2022))

alluvial_part_com

ggsave(alluvial_part_com, file="output/graphs/alluvial_part_com.png", height = 8, width = 7)
```

```{r bivariate-plots-part-com}
df_study1 <- df_study1_long_t6 %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                               part_com, starts_with("barrio_"),
                                                educ, quintil1, ess, edad, sexo, pos_id) %>% na.omit()
cohesion_plot <- df_study1 %>% 
  select(starts_with("barrio_"), starts_with("satisfaccion_")) %>% 
  sjPlot::plot_stackfrq(weight.by = df_study1$ponderador_long_total,
                        expand.grid =TRUE,
                      geom.colors = "PuBu",
                      show.total = FALSE, 
         #             vjust=rep(c("bottom", "top", "bottom", "top", "bottom"),4),
                      legend.labels = c("Muy en desacuerdo", "Desacuerdo", "Ni de acuerdo
Ni desacuerdo", "De acuerdo", "Muy de acuerdo"),
#                       axis.labels = c("Merit effort", "Merit talent", "Inequality 
# perception", "Justification 
# of 
# educational inequality")
                      ) +
  theme_light(base_size = 16) +
  theme(legend.position="bottom", text = element_text(size = 14),
        plot.caption = element_text(hjust = 1))
cohesion_plot

ggsave(cohesion_plot, file="output/graphs/cohesion_plot.png", height = 6, width = 10)
```

```{r bivariate-plots2-part-com}
df_study1 <- df_study1_long_t6 %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                               part_com, starts_with("satisfaccion_"),
                                                educ, quintil1, ess, edad, sexo, pos_id) %>% na.omit()
satisfaccion_plot <- df_study1 %>% 
  select(starts_with("barrio_"), starts_with("satisfaccion_")) %>% 
  sjPlot::plot_stackfrq(weight.by = df_study1$ponderador_long_total,
                        expand.grid =TRUE,
                      geom.colors = "PuBu",
                      show.total = FALSE, 
         #             vjust=rep(c("bottom", "top", "bottom", "top", "bottom"),4),
                      legend.labels = c("Muy en desacuerdo", "Desacuerdo", "Ni de acuerdo
Ni desacuerdo", "De acuerdo", "Muy de acuerdp"),
#                       axis.labels = c("Merit effort", "Merit talent", "Inequality 
# perception", "Justification 
# of 
# educational inequality")
                      ) +
  theme_light(base_size = 16) +
  theme(legend.position="bottom", text = element_text(size = 14),
        plot.caption = element_text(hjust = 1))
satisfaccion_plot

ggsave(satisfaccion_plot, file="output/graphs/satisfaccion_plot.png", height = 6, width = 10)
```


## Regresión


```{r part_com}
rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study1_long_t6.RData"))

# generate analytical sample
df_study1 <- 
  df_study1_long_t6 %>%
  select(idencuesta,ola,comuna, region_cod, ponderador_long_total, part_com, starts_with("barrio_"), starts_with("satisfaccion_"), educ, quintil1, ess, edad, sexo, pos_id) %>% 
  na.omit() %>% 
  mutate(ola_num=as.numeric(ola),
         ola_2 = ola_num^2,
         ola=as.factor(ola),
         sexo=as.factor(sexo)
         )
# Hipotesis
h1 <- "ola"
h2 <- "ola_num"
h3 <- "ola_2"
h4 <- "ola_num+ola_2"

part_com.null <- lmer(formula(paste0("part_com~","1 + (1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com1 <- lmer(formula(paste0("part_com~",h1,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com2 <- lmer(formula(paste0("part_com~",h2,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com3 <- lmer(formula(paste0("part_com~",h3,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com4 <- lmer(formula(paste0("part_com~",h4,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)

performance::icc(part_com.null)
```


```{r part_com-reg, results='asis'}
texreg::htmlreg(list(part_com.null, part_com1, part_com2, part_com3, part_com4),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05")
```


```{r part_com2}
sjmisc::frq(df_study1$region_cod)
df_study1 <- df_study1 %>% mutate(rm= case_when(region_cod==13~"RM",
                                                TRUE~"Otra región"))
sjmisc::frq(df_study1$rm)

df_study1 <- df_study1 %>% 
  rowwise() %>%
  mutate(cohesion_barrial = mean(c(barrio_ideal, barrio_integrado, barrio_identifico, barrio_partedemi)),
         sociabilidad_barrial = mean(c(barrio_amigos, barrio_sociable, barrio_cordial, barrio_colaboradora)),
         satisfaccion_residencial= mean(c(satisfaccion_seguridad, satisfaccion_conectivdad, satisfaccion_areasverdes, satisfaccion_limpieza, satisfaccion_proximidadtrabajo, satisfaccion_proximidadcolegios, satisfaccion_proximidadcomercio, satisfaccion_proximidadfamilia))) %>% 
  ungroup()


h5 <- "ola+edad"
h6 <- "ola+edad+rm"
h7 <- "ola+edad+rm+cohesion_barrial"
h8 <- "ola+edad+rm+sociabilidad_barrial"
h9 <- "ola+edad+rm+satisfaccion_residencial"
h10 <- "ola+edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial"
h11 <- "ola+edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"
h12 <- "ola*edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"
h13 <- "ola*educ+edad+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"
h14 <- "edad*educ*ola+rm+cohesion_barrial+sociabilidad_barrial+satisfaccion_residencial+educ+quintil1+sexo+ess+pos_id"

# A. Education distributive justice

part_com5 <- lmer(formula(paste0("part_com~",h5,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com6 <- lmer(formula(paste0("part_com~",h6,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com7 <- lmer(formula(paste0("part_com~",h7,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com8 <- lmer(formula(paste0("part_com~",h8,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com9 <- lmer(formula(paste0("part_com~",h9,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com10 <- lmer(formula(paste0("part_com~",h10,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com11 <- lmer(formula(paste0("part_com~",h11,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com12 <- lmer(formula(paste0("part_com~",h12,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com13 <- lmer(formula(paste0("part_com~",h13,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
part_com14 <- lmer(formula(paste0("part_com~",h14,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
```

### Modelos de regresión

```{r part_com2-reg, results='asis'}
#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(part_com1, part_com5, part_com6, part_com7, part_com8, part_com9, part_com10, part_com11),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
#                custom.coef.names = c("Intercepto",
#                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
#                                      "ola 2018",
#                                      "ola 2019",
##                                      "ola 2022",
#                                      "Merito: esfuerzo",
#                                      "Merito: Inteligencia",
##                                      "Goahead: Familia",
#                                      "Goahead: educacion",
#                                      "Goahead: ambicion",
#                                      "Goahead: trabajo duro",
#                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
#                                      "Ed. técnica",
#                                      "Ed. universitaria",
#                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
#                                      "Quintil 3",
#                                      "Quintil 4",
#                                      "Quintil 5",
#                                      "Quintil NA",
#                                      "Estatus social subjetivo",
#                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
#                                      "Pos. política: Derecha",
#                                      "Pos. política: No se identifica",
#                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
#                                      "Edad 50-64",
#                                      "Edad 65 o más",
#                                      "Mujer <br> <i>(Ref. Hombre)</i>",
#                                      "Gini comunal",
#                                      "Cambio gini 2022-2017",
#                                      "Proporción educ universitaria",
#                                      "Proporción matrícula privada",
#                                      "Total matrícula privada",
#                                      "Varianza Simce comuna",
#                                      "Promedio Simce comuna"
                                    
                              )
          #omit.coef = omit

```

### interacciones

```{r part_com-interac, results='asis'}
#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(part_com12, part_com13, part_com14),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
#                custom.coef.names = c("Intercepto",
#                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
#                                      "ola 2018",
#                                      "ola 2019",
##                                      "ola 2022",
#                                      "Merito: esfuerzo",
#                                      "Merito: Inteligencia",
##                                      "Goahead: Familia",
#                                      "Goahead: educacion",
#                                      "Goahead: ambicion",
#                                      "Goahead: trabajo duro",
#                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
#                                      "Ed. técnica",
#                                      "Ed. universitaria",
#                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
#                                      "Quintil 3",
#                                      "Quintil 4",
#                                      "Quintil 5",
#                                      "Quintil NA",
#                                      "Estatus social subjetivo",
#                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
#                                      "Pos. política: Derecha",
#                                      "Pos. política: No se identifica",
#                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
#                                      "Edad 50-64",
#                                      "Edad 65 o más",
#                                      "Mujer <br> <i>(Ref. Hombre)</i>",
#                                      "Gini comunal",
#                                      "Cambio gini 2022-2017",
#                                      "Proporción educ universitaria",
#                                      "Proporción matrícula privada",
#                                      "Total matrícula privada",
#                                      "Varianza Simce comuna",
#                                      "Promedio Simce comuna"
                                    
                              )
          #omit.coef = omit

```

```{r}
sjPlot::plot_model(part_com12, type = "int")
```


```{r}
sjPlot::plot_model(part_com13, type = "int")
```

```{r}
sjPlot::plot_model(part_com14, type = "int")
```

