---
title: "03-resultados"
format: html
editor: source
---

```{r}
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               ggplot2,
               sjPlot,
               tidyverse,
               ggalluvial,
               survey,
               shadowtext,
               srvyr,
               interactions,
               lme4
               )
```

```{r}
load(file = here::here("input/data-proc/df_study1_long_t7.RData"))
df_study1 <- df_study1_long_t7 %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                                marchar,
         barrio_ideal,
         barrio_integrado,
         barrio_identifico,
         barrio_partedemi,
         barrio_amigos,
         barrio_sociable,
         barrio_cordial,
         barrio_colaboradora,
         satisfaccion_proximidadtrabajo,
         satisfaccion_proximidadcolegios,
         satisfaccion_proximidadcomercio,
         satisfaccion_seguridad,
         jjvv_prom,
         org_religiosa_prom,
         org_caridad_prom,
         org_deportiva_prom,
                                                educ, quintil1, ess, edad, sexo, pos_id) %>% na.omit()
df_study1 <- df_study1[complete.cases(df_study1$segmento), ]

df_study1$marchar <- factor(df_study1$marchar,
         labels = c("Nunca", "Casi nunca", "A veces", "Frecuentemente", "Muy 
frecuentemente"))

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador_long_total, #ponderador longitudinal
                          nest = TRUE,
                          data = df_study1)


#Paso 1
datos.marchar <- data.frame((svytable(~marchar + ola + idencuesta, elsoc_diseno, round = F))) %>% dplyr::filter(Freq>0)  %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#Paso 2
etiquetas.marchar <- data.frame((svytable(~marchar + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit() %>% 
  mutate(idencuesta = 1)
datos.marchar$marchar <- factor(datos.marchar$marchar, levels = rev(levels(datos.marchar$marchar)))
etiquetas.marchar$marchar <- factor(etiquetas.marchar$marchar, levels = rev(levels(etiquetas.marchar$marchar)))
```

```{r alluvial}
colors<- c("#f1eef6ff","#bdc9e1ff","#b3b3b3ff","#74a9cfff","#0570b0ff")
alluvial_marchar <- ggplot(datos.marchar, aes(x = ola, fill = marchar, stratum = marchar,
                             alluvium = idencuesta, y = porcentaje))+
    ggalluvial::geom_flow(alpha = .66) + 
    ggalluvial::geom_stratum(linetype = 0) +
    scale_y_continuous(labels = scales::percent) + 
    ylab(label = NULL) +
    xlab(label = NULL) + 
    theme(#legend.position = 'top',
          legend.title = element_blank(),
          plot.caption = element_text(hjust = 1)) +
    scale_fill_manual(values = colors) +
    geom_shadowtext(data = etiquetas.marchar, 
              aes(label = ifelse(porcentaje > 0 , scales::percent(porcentaje, accuracy = .1),"")),
              position = position_stack(vjust = .5),
              show.legend = FALSE,
              size = 4,
              color = rep('white'),
              bg.colour='grey30')+
  scale_x_discrete(labels = c(2016, 2017, 2018, 2019, 2022, 2023))

alluvial_marchar
```

```{r}
rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study1_long_t7.RData"))

# generate analytical sample
df_study1 <- 
  df_study1_long_t7 %>%
  select(idencuesta,ola,comuna, region_cod, ponderador_long_total, marchar, part_com, satisfaccion_seguridad, starts_with("barrio_"), jjvv_prom, org_religiosa_prom, org_caridad_prom, org_deportiva_prom, educ, quintil1, ess, edad, sexo, pos_id) %>% 
  na.omit() %>% 
  mutate(ola_num=as.numeric(ola),
         ola_2 = ola_num^2,
         ola=as.factor(ola),
         sexo=as.factor(sexo)
         )
df_study1 <- df_study1 %>% mutate(rm= case_when(region_cod==13~"RM",
                                                TRUE~"Otra región"))

df_study1 <- df_study1 %>% 
  rowwise() %>%
  mutate(attachment = mean(c(barrio_ideal, barrio_integrado, barrio_identifico, barrio_partedemi, na.rm=TRUE)),
         sociabilidad = mean(c(barrio_amigos, barrio_sociable, barrio_cordial, barrio_colaboradora, na.rm=TRUE))) %>% 
  ungroup()

h5 <- "ola+edad"
h6 <- "ola+edad+rm"
h7 <- "ola+edad+rm+satisfaccion_seguridad"
h8 <- "ola+edad+rm+attachment"
h9 <- "ola+edad+rm+sociabilidad"
h10 <- "ola+edad+rm+part_com"
h11 <- "ola+edad+rm+jjvv_prom"
h12 <- "ola+edad+rm+org_religiosa_prom"
h13 <- "ola+edad+rm+org_caridad_prom"
h14 <- "ola+edad+rm+org_deportiva_prom"
h15 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom"
h16 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id"
h17 <- "ola*edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id"
h18 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*satisfaccion_seguridad"
h19 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*attachment"
h20 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*sociabilidad"
h21 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*part_com"
h22 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*jjvv_prom"
h23 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*org_religiosa_prom"
h24 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*org_caridad_prom"
h25 <- "ola+edad+rm+satisfaccion_seguridad+attachment+sociabilidad+part_com+jjvv_prom+org_religiosa_prom+org_caridad_prom+org_deportiva_prom+educ+quintil1+sexo+pos_id+edad*org_deportiva_prom"

marchar5 <- lmer(formula(paste0("marchar~",h5,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar6 <- lmer(formula(paste0("marchar~",h6,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar7 <- lmer(formula(paste0("marchar~",h7,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar8 <- lmer(formula(paste0("marchar~",h8,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar9 <- lmer(formula(paste0("marchar~",h9,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar10 <- lmer(formula(paste0("marchar~",h10,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar11 <- lmer(formula(paste0("marchar~",h11,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar12 <- lmer(formula(paste0("marchar~",h12,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar13 <- lmer(formula(paste0("marchar~",h13,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar14 <- lmer(formula(paste0("marchar~",h14,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar15 <- lmer(formula(paste0("marchar~",h15,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar16 <- lmer(formula(paste0("marchar~",h16,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar17 <- lmer(formula(paste0("marchar~",h17,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar18 <- lmer(formula(paste0("marchar~",h18,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar19 <- lmer(formula(paste0("marchar~",h19,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar20 <- lmer(formula(paste0("marchar~",h20,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar21 <- lmer(formula(paste0("marchar~",h21,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar22 <- lmer(formula(paste0("marchar~",h22,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar23 <- lmer(formula(paste0("marchar~",h23,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar24 <- lmer(formula(paste0("marchar~",h24,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar25 <- lmer(formula(paste0("marchar~",h25,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
```

```{r marchar2-reg, results='asis'}
#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(marchar5, marchar6, marchar7, marchar8, marchar9, marchar10, marchar11, marchar12, marchar13, marchar14, marchar15, marchar16),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
#                custom.coef.names = c("Intercepto",
#                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
#                                      "ola 2018",
#                                      "ola 2019",
##                                      "ola 2022",
#                                      "Merito: esfuerzo",
#                                      "Merito: Inteligencia",
##                                      "Goahead: Familia",
#                                      "Goahead: educacion",
#                                      "Goahead: ambicion",
#                                      "Goahead: trabajo duro",
#                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
#                                      "Ed. técnica",
#                                      "Ed. universitaria",
#                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
#                                      "Quintil 3",
#                                      "Quintil 4",
#                                      "Quintil 5",
#                                      "Quintil NA",
#                                      "Estatus social subjetivo",
#                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
#                                      "Pos. política: Derecha",
#                                      "Pos. política: No se identifica",
#                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
#                                      "Edad 50-64",
#                                      "Edad 65 o más",
#                                      "Mujer <br> <i>(Ref. Hombre)</i>",
#                                      "Gini comunal",
#                                      "Cambio gini 2022-2017",
#                                      "Proporción educ universitaria",
#                                      "Proporción matrícula privada",
#                                      "Total matrícula privada",
#                                      "Varianza Simce comuna",
#                                      "Promedio Simce comuna"
                                    
                              )
          #omit.coef = omit

```

```{r}
marchar17 <- lmer(formula(paste0("marchar~",h17,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar18 <- lmer(formula(paste0("marchar~",h18,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar19 <- lmer(formula(paste0("marchar~",h19,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar20 <- lmer(formula(paste0("marchar~",h20,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar21 <- lmer(formula(paste0("marchar~",h21,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar22 <- lmer(formula(paste0("marchar~",h22,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar23 <- lmer(formula(paste0("marchar~",h23,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar24 <- lmer(formula(paste0("marchar~",h24,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
marchar25 <- lmer(formula(paste0("marchar~",h25,"+(1|idencuesta)")),data = df_study1, weights = ponderador_long_total)
```

```{r marchar-interac, results='asis'}
#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(marchar16, marchar17, marchar18, marchar19, marchar20,
                     marchar21,marchar22,marchar23,marchar24,marchar25),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
#                custom.coef.names = c("Intercepto",
#                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
#                                      "ola 2018",
#                                      "ola 2019",
##                                      "ola 2022",
#                                      "Merito: esfuerzo",
#                                      "Merito: Inteligencia",
##                                      "Goahead: Familia",
#                                      "Goahead: educacion",
#                                      "Goahead: ambicion",
#                                      "Goahead: trabajo duro",
#                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
#                                      "Ed. técnica",
#                                      "Ed. universitaria",
#                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
#                                      "Quintil 3",
#                                      "Quintil 4",
#                                      "Quintil 5",
#                                      "Quintil NA",
#                                      "Estatus social subjetivo",
#                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
#                                      "Pos. política: Derecha",
#                                      "Pos. política: No se identifica",
#                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
#                                      "Edad 50-64",
#                                      "Edad 65 o más",
#                                      "Mujer <br> <i>(Ref. Hombre)</i>",
#                                      "Gini comunal",
#                                      "Cambio gini 2022-2017",
#                                      "Proporción educ universitaria",
#                                      "Proporción matrícula privada",
#                                      "Total matrícula privada",
#                                      "Varianza Simce comuna",
#                                      "Promedio Simce comuna"
                                    
                              )
          #omit.coef = omit

```

ola x edad

```{r}
interact_plot(marchar17, pred = edad, modx = ola, interval = TRUE)
```

satisfaccion seguridad x edad

```{r}
interact_plot(marchar18, pred = satisfaccion_seguridad, modx = edad, jnplot = TRUE, interval = TRUE)
```

attachment x edad

```{r}
interact_plot(marchar19, pred = attachment, modx = edad, jnplot = TRUE, interval = TRUE)
```

sociabilidad x edad

```{r}
interact_plot(marchar20, pred = sociabilidad, modx = edad, jnplot = TRUE, interval = TRUE)
```

part_com x edad

```{r}
interact_plot(marchar21, pred = part_com, modx = edad, jnplot = TRUE, interval = TRUE)
```

jjvv_prom x edad

```{r}
interact_plot(marchar22, pred = jjvv_prom, modx = edad, jnplot = TRUE, interval = TRUE)
```

org_religiosa_prom x edad

```{r}
interact_plot(marchar23, pred = org_religiosa_prom, modx = edad, jnplot = TRUE, interval = TRUE)
```

org_caridad_prom x edad

```{r}
interact_plot(marchar24, pred = org_caridad_prom, modx = edad, jnplot = TRUE, interval = TRUE)
```

org_deportiva_prom x edad

```{r}
interact_plot(marchar25, pred = org_deportiva_prom, modx = edad, jnplot = TRUE, interval = TRUE)
```
